LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

LIBRARY UTILITIES;
USE UTILITIES.UTILITIES.ALL;

ENTITY GEN_IO_CLK IS
	GENERIC(
		CONSTANT MAX_COUNT : POSITIVE RANGE 3 TO POSITIVE'HIGH
	);
	PORT (
		SIGNAL RST    : IN STD_LOGIC;
		SIGNAL CLK    : IN STD_LOGIC;
		SIGNAL IO_CLK : OUT STD_LOGIC
	);
END ENTITY GEN_IO_CLK;

ARCHITECTURE UNIQUE OF GEN_IO_CLK IS
	
	CONSTANT C_WIDTH : POSITIVE := CLOG2(MAX_COUNT);
	CONSTANT C_MSB   : POSITIVE := C_WIDTH - 1;
	SUBTYPE REG_COUNTER_t IS UNSIGNED(C_MSB DOWNTO 0);
	
	SIGNAL S_COUNTER : REG_COUNTER_t;
	SIGNAL S_IO_CLK  : STD_LOGIC;

BEGIN

	PROCESS(RST, CLK) IS
	BEGIN
		IF RST = '1' THEN
			S_COUNTER <= TO_UNSIGNED(MAX_COUNT,C_WIDTH);
			S_IO_CLK <= '0';
			IO_CLK <= '0';
		ELSIF RISING_EDGE(CLK) THEN
			IF S_COUNTER /= 0 THEN
				S_COUNTER <= S_COUNTER - 1;
				IO_CLK <= S_IO_CLK;
			ELSE
				S_COUNTER <= TO_UNSIGNED(MAX_COUNT,C_WIDTH);
				S_IO_CLK <= NOT S_IO_CLK;
				IO_CLK <= NOT S_IO_CLK;
			END IF;
		END IF;
		
	END PROCESS;

END ARCHITECTURE UNIQUE;

