
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

LIBRARY UTILITIES;
USE UTILITIES.UTILITIES.ALL;

PACKAGE SYSTEM_CONSTANTS IS
	
	-- FRECUENCIA DEL CRISTAL
	CONSTANT C_FREC        : INTEGER := 50_000_000;-- HERZIOS INICIALES
	-- NUMERO DE VECES QUE QUEREMOS QUE PARPADEE EN UN SEGUNDO
	CONSTANT C_REFRESH     : INTEGER := 500;-- HERZIOS
	-- DETERMINAMOS LA CUANTA MÁXIMA
	CONSTANT C_MAX_COUNT   : INTEGER := C_FREC/C_REFRESH; --100_000, T = 2 * 10^(-3) = 2MS, F = 500HZ
	-- DETERMINAMOS EL MSB
	CONSTANT C_MSB : INTEGER := CLOG2(C_MAX_COUNT);
	-- TENEMOS EL TIPO REGISTRO PARA CONTAR
	SUBTYPE REG_COUNTER_T IS UNSIGNED(C_MSB DOWNTO 0);
	
	CONSTANT C_ZERO : REG_COUNTER_T := TO_UNSIGNED(0,C_MSB+1);
	
	CONSTANT C_ONE : REG_COUNTER_T := TO_UNSIGNED(1,C_MSB+1);

END PACKAGE SYSTEM_CONSTANTS;

PACKAGE BODY SYSTEM_CONSTANTS IS

END PACKAGE BODY SYSTEM_CONSTANTS;
